spring.application.name: employee-api
server.port: 8111

employee:
  client:
    base-url: http://localhost:8112/api/v1/employee
    connect-timeout: 5s
    read-timeout: 10s
    retry:
      max-attempts: 3
      delay: 500
      multiplier: 2.0

api:
  retry-after-seconds: 5
